export const FORECAST_NAME = 'FORECAST';
export const FORECAST_MONTHLY_NAME = 'FORECAST-MONTHLY';
export const FORECAST_YEARLY_NAME = 'FORECAST-YEARLY';
export const FORECAST_TREE_UNIQUE_DATE = 'FORECAST-TREE-UNIQUE-DATE';
export const NETWORK_NAME = 'NETWORK';
export const SCENARIO_1P_1C = '1P_1C';
export const SCENARIO_2P_2C = '2P_2C';
export const SCENARIO_3P_3C = '3P_3C';

export const ALL_SCENARIO_NAMES = [
  SCENARIO_1P_1C,
  SCENARIO_2P_2C,
  SCENARIO_3P_3C,
];
